### ISSUE TITLE
in_data_dir in canopy does not end in "/", breaking backwards combability with bronx analysis scripts

### ISSUE THREAD

**Issue by uwagura** [NOAA-GFDL/fre-workflows#17]
This is _veeeerrrry_ minor, but when canopy sets the `in_data_dir` variable in analysis scripts, it does not include a backslash at the end, even though `fre/bronx` included this character

https://github.com/NOAA-GFDL/fre-workflows/blob/c18dedd918a09fef11a24ffcab692ab8d86a3e7b/Jinja2Filters/get_analysis_info.py#L343-L347

This means that any bronx analysis scripts that were written under the assumption that the `in_data_dir` path would end in a backslash character won't work in canopy. 

If fixing this issue will cause other things to break because they assume that `in_data_dir` doesn't end in a backslash, we could honestly just tell users to manually add a backslash character in any scripts they have that use the `in_data_dir` variable, but I though I'd bring it anyways.

**Comment by ceblanton** [comment]
Also, use os.path or Path
