### ISSUE TITLE
Potential bad paths in remap-pp-components

### ISSUE THREAD

**Issue by menzel-gfdl** [NOAA-GFDL/fre-workflows#9]
The `if` condition is not correct here:

https://github.com/NOAA-GFDL/fre-workflows/blob/main/app/remap-pp-components/bin/remap-pp-components#L452

It should read `if ens_mem is None`.  Also, can we change those `check=False` options to `check=True`?  That should make the script fail instead of saying it passes.

**Comment by ilaflott** [comment]
updated original issue text w/ permalink. without it- the initial issue is not clear.
